name: Build LumberRacer EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # تغییر این بخش به 4.8 چون 4.5 دیگر موجود نیست
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y

    - name: Restore NuGet packages
      run: nuget restore LumberRacer.sln

    - name: Build solution
      run: msbuild LumberRacer.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: LumberRacer-exe
        path: |
          **/bin/Release/*.exe
